require("core.plugin_config.lualine")
require("core.plugin_config.nordic")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.tree-sitter")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp-config")
